apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: votrix-backend-staging
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "3"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 900
      containers:
        - image: IMAGE_URL
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: database-url-staging
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: anthropic-api-key
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: supabase-url-staging
            - name: SUPABASE_SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: supabase-service-key-staging
            - name: COMPOSIO_API_KEY
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: composio-api-key
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: gemini-api-key
            - name: DEBUG
              value: "true"
